// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDamOqwRJHJhKvBmGGYIeSgsuUWm4Q04s',
    appId: '1:939816788196:web:854c8b5b32a2f947118cf1',
    messagingSenderId: '939816788196',
    projectId: 'reizoukoban-app',
    authDomain: 'reizoukoban-app.firebaseapp.com',
    storageBucket: 'reizoukoban-app.firebasestorage.app',
    measurementId: 'G-W7SXS8M0YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg0xf5gzJoJxI9YaljORiyXWjYGKX4pmA',
    appId: '1:939816788196:android:0f5baff3d18fe9d8118cf1',
    messagingSenderId: '939816788196',
    projectId: 'reizoukoban-app',
    storageBucket: 'reizoukoban-app.firebasestorage.app',
  );
}
